type: module
name: UD paragraphs migration configuration
description: 'Exported configuration for paragraph migration examples. Learn more at <a href="https://understanddrupal.com/migrations" title="Drupal Migrations">https://understanddrupal.com/migrations</a>.'
package: Understand Drupal
core: 8.x
core_version_requirement: ^8 || ^9 || ^10
dependencies:
  - entity_reference_revisions:entity_reference_revisions
  - paragraphs:paragraphs
